### ISSUE TITLE
Tenant delete not working without --no-verifier-check

### ISSUE THREAD

**Issue by ljmcgann** [keylime/keylime#705]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Fedora
 * Processor architecture: 
 * TPM Manufacturer: tpm2-emulator
 * Keylime version: 16a9cfd

# Description 

If the verifier is hosted on a different machine than where the tenant is called, the keylime_tenant -c delete command will not work without the --no-verifier-check flag. This is because of the line of code here

https://github.com/keylime/keylime/blob/115d9cf7b4d2e7a25fbc61fca2b1eb6e5ce74e52/keylime/tenant.py#L655

When calling the tenant with a verifier flag for a verifier not in the CONF file, the tenant will first retrieve the status from the verifier. The tenant then uses the verifier address returned by the verifier as opposed to the address passed in the command line. The result is the status check passes, but the delete check fails to connect and shows a url that differs from what was passed in. In our case we had our CONF file set to 0.0.0.0

## Expected behavior vs. actual behavior 

Expected: delete command works without --no-verifier-check
Actual: --no-verifier-check flag is needed.

## Steps to reproduce problem
1. Stand up a verifier with address 0.0.0.0
2. Call delete to the verifier using the tenant on a different machine than where the verifier is set up

# Relevant logs

Attach any relevant log files that can help to debug your issue. 

HTTPSConnectionPool(host=\'0.0.0.0\', port=8881): Max retries exceeded with url: /agents/4c4c4544-0034-4410-8056-cac04f4d3032 (Caused by NewConnectionError(\'<urllib3.connection.HTTPSConnection object at 0x7fd82565edd8>: Failed to establish a new connection: [Errno 111] Connection refused\

**Comment by maugustosilva** [comment]
@apoorvemohan This is related to the "single database for multiple verifiers" introduced by your PR.
@ljmcgann @mpeters I see this as a problem of documentation, instead of code. My proposal is to add a message alongside the following lines: "it was not possible to connect to `verifier` at `<IP>:<port>`. If you are attempt to contact a `verifier` directly - without a load balancer in front of it, please add the `--no-verifier-check` flag`"

**Comment by apoorvemohan** [comment]
> HTTPSConnectionPool(host='0.0.0.0', port=8881): Max retries exceeded with url: /agents/4c4c4544-0034-4410-8056-cac04f4d3032 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd82565edd8>: Failed to establish a new connection: [Errno 111] Connection refused\

@ljmcgann Can you share the tenant command?

**Comment by ljmcgann** [comment]
Thanks for getting back to me @maugustosilva. Could you clarify what this flag does that it requires a load balancer on the veriifer?

**Comment by ljmcgann** [comment]
@apoorvemohan
keylime_tenant -c delete -v "172.16.100.206" -vp 8881 -u 4c4c4544-0034-4410-8056-cac04f4d3032

The CONF file the vm with our verifier has its address set to 0.0.0.0.

**Comment by apoorvemohan** [comment]
@ljmcgann In the CONF on the verifier, if you specify "172.16.100.206" instead of "0.0.0.0", do you still see the error?

**Comment by ljmcgann** [comment]
@apoorvemohan Setting the verifier to 172.16.100.206 makes it not require the --no-verifier-check flag

**Comment by mpeters** [comment]
Setting IPs to `0.0.0.0` is a very common thing to make systems work where multiple IPs on the host might be involed. We need to make sure it's something that is supported.

**Comment by maugustosilva** [comment]
> Thanks for getting back to me @maugustosilva. Could you clarify what this flag does that it requires a load balancer on the veriifer?

The main idea behind the *absence* of the `--no-verifier-check` is that `keylime_tenant` will, in case of `delete` operation, query the current status of the `agent`, in order to figure out which `verifier` the `agent` belongs to, before actually issuing the delete. Obviously, this means that the `-v` parameter might be dynamically overridden if needed.

**Comment by apoorvemohan** [comment]
> Setting IPs to `0.0.0.0` is a very common thing to make systems work where multiple IPs on the host might be involed. We need to make sure it's something that is supported.

We can support this by having a different bind and public ip fields as suggested [here](https://github.com/keylime/keylime/issues/441#issuecomment-743029548).

**Comment by mpeters** [comment]
My guess @maugustosilva and @apoorvemohan is that this can be closed since the bind addresses for each service part has been merged.

**Comment by THS-on** [comment]
@maugustosilva can you confirm this is fixed?

**Comment by maugustosilva** [comment]
Not solved yet. Solution seems to be simple, will do it promptly.
